INSERT INTO "kategorie_schlagwoerter" VALUES(1,'DEUTSCHE BANK',13);
INSERT INTO "kategorie_schlagwoerter" VALUES(2,'Konsum',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(3,'49001819 PETERSBOGEN',13);
INSERT INTO "kategorie_schlagwoerter" VALUES(4,'7camicie',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(5,'A.T.U.',2);
INSERT INTO "kategorie_schlagwoerter" VALUES(6,'ABOUTYOU',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(7,'ALDI',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(8,'ALEX LEIPZIG',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(9,'ALPENTAXI',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(10,'AMAZON',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(11,'AMZ',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(12,'APCOA',16);
INSERT INTO "kategorie_schlagwoerter" VALUES(13,'ARAL',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(14,'Apotheke',17);
INSERT INTO "kategorie_schlagwoerter" VALUES(15,'Agip',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(16,'PARKHAUS',16);
INSERT INTO "kategorie_schlagwoerter" VALUES(17,'Asia Mekong',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(18,'BACKHAUS HENNIG',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(19,'BAD SAAROW',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(20,'BAECKEREI & KONDITOREI',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(21,'BAGEL BROTHERS',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(22,'BIEDERMANNHOF',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(23,'BK',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(24,'BP',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(25,'BRENNERO',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(26,'BROT UND KEES',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(27,'BUNDESAMT FUER JUSTIZ',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(28,'BURGER KING',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(29,'BackWerk',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(30,'Beyerhaus',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(31,'Bike Department Ost GmbH',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(32,'Blumen & Floristik Koenig',14);
INSERT INTO "kategorie_schlagwoerter" VALUES(33,'Brauhaus Napoleon',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(34,'CAFE MADRID',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(35,'CAFE'' VICOLO',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(36,'CARTRIDGE CARE LEIPZIG',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(37,'CENTER PARCS BUNGALOWP',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(38,'CESKA POSTA',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(39,'CHATGPT',12);
INSERT INTO "kategorie_schlagwoerter" VALUES(40,'COFFEE FELLOWS',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(41,'CONTIPARK',16);
INSERT INTO "kategorie_schlagwoerter" VALUES(42,'Cafe im Bahnhof',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(43,'Center Parcs',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(44,'Champagnerclub',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(45,'Champagnerhuette OG',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(46,'Ad free for',12);
INSERT INTO "kategorie_schlagwoerter" VALUES(47,'Alnatura',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(48,'BACKALLERLEI',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(49,'14 Balice Manual (2)',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(50,'16 Brzeczkowice Manual (2',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(51,'6 Balice Manual (2)',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(52,'6 Brzeczkowice Manual (2)',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(53,'DB ZUGVERKAUF',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(54,'DECATHLON',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(55,'DENSG MICHENDORF GMBH',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(56,'DM Drogerie Markt',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(57,'DM-Drogerie Markt',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(58,'DRESDNER VERKEHR',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(59,'BAUHAUS',5);
INSERT INTO "kategorie_schlagwoerter" VALUES(60,'Das Taubchenthal',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(61,'Dean & David',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(62,'Dhillon''s',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(63,'Die erste Leipziger Brots',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(64,'Dunkin Donuts',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(65,'Daenisches Bettenlager',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(66,'EDALNICE',2);
INSERT INTO "kategorie_schlagwoerter" VALUES(67,'EDEKA',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(68,'ESSO',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(69,'EVIVA SPORT GMBH',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(70,'DB BAHN',18);
INSERT INTO "kategorie_schlagwoerter" VALUES(71,'DB Vertrieb',18);
INSERT INTO "kategorie_schlagwoerter" VALUES(72,'FLOWER BURGER',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(73,'FREE FLOW FRANKENHOEHE NO',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(74,'FREIE SERVICE STATION',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(75,'Flughafen Leipzig/Halle G',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(76,'Frisoer Katrin Sauer',11);
INSERT INTO "kategorie_schlagwoerter" VALUES(77,'GALERIA KAUFHOF',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(78,'GCM GASTRO CONCEPT MAN',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(79,'GERD LIEBIG GMBH',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(80,'GERD VOGEL',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(81,'GEWANDHAUS ZU LEIPZIG',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(82,'GOESSER ECK',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(83,'GOLDHOPFEN',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(84,'Europcar',20);
INSERT INTO "kategorie_schlagwoerter" VALUES(85,'GOOGLE  Google Storage',1);
INSERT INTO "kategorie_schlagwoerter" VALUES(86,'GOOGLE  Google Storage',12);
INSERT INTO "kategorie_schlagwoerter" VALUES(87,'GOOGLE  Google Play Ap',21);
INSERT INTO "kategorie_schlagwoerter" VALUES(88,'GOOGLE *Google Play Ap',21);
INSERT INTO "kategorie_schlagwoerter" VALUES(89,'GOOGLE *Google Storage',12);
INSERT INTO "kategorie_schlagwoerter" VALUES(90,'GOOGLE*GOOGLE PLAY APP',21);
INSERT INTO "kategorie_schlagwoerter" VALUES(91,'GOOGLE*GOOGLE STORAGE',12);
INSERT INTO "kategorie_schlagwoerter" VALUES(92,'GOOGLE*YOUTUBE',12);
INSERT INTO "kategorie_schlagwoerter" VALUES(93,'GREIFHAUS',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(94,'GUESS FREEPORT HATE',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(95,'Globus Baumarkt',5);
INSERT INTO "kategorie_schlagwoerter" VALUES(96,'Goethe Schokoladentaler',14);
INSERT INTO "kategorie_schlagwoerter" VALUES(97,'Google Payment IrelandLTD',21);
INSERT INTO "kategorie_schlagwoerter" VALUES(98,'Google Store',21);
INSERT INTO "kategorie_schlagwoerter" VALUES(99,'Gourm tage',14);
INSERT INTO "kategorie_schlagwoerter" VALUES(100,'Gourmetage',14);
INSERT INTO "kategorie_schlagwoerter" VALUES(101,'Groschen-Hausrat Discount',7);
INSERT INTO "kategorie_schlagwoerter" VALUES(102,'H&amp;M',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(103,'HANS IM GLUECK',9);
INSERT INTO "kategorie_schlagwoerter" VALUES(104,'Google Payment IE LTD Goo',21);
INSERT INTO "kategorie_schlagwoerter" VALUES(105,'HEM',3);
INSERT INTO "kategorie_schlagwoerter" VALUES(106,'IKEA',4);
INSERT INTO "kategorie_schlagwoerter" VALUES(107,'HILLIS GRILL & BAR',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(108,'HKL BAUMASCHINEN',6);
INSERT INTO "kategorie_schlagwoerter" VALUES(109,'LOSTERIA',15);
INSERT INTO "kategorie_schlagwoerter" VALUES(110,'FOTAXI ZRT',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(111,'HOYER AUTOHOF SOLTAU',2);
INSERT INTO "kategorie_schlagwoerter" VALUES(112,'HUGENDUBEL',14);
INSERT INTO "kategorie_schlagwoerter" VALUES(113,'Hornbach',5);
INSERT INTO "kategorie_schlagwoerter" VALUES(114,'ALBERT VAM DEKUJE',10);
INSERT INTO "kategorie_schlagwoerter" VALUES(115,'3%  Entgelt Casino / Lott',19);
INSERT INTO "kategorie_schlagwoerter" VALUES(116,'Hussel',14);
INSERT INTO "kategorie_schlagwoerter" VALUES(117,'Huwa GmbH',15);
